# Generated by Django 4.2 on 2023-05-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_playerdemography_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdemography',
            name='ethnicity',
        ),
    ]
