# Generated by Django 4.2 on 2023-06-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_playerdemography_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
