# Generated by Django 4.2 on 2023-06-21 05:55

from django.db import migrations, models
import report.validators


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0004_alter_entry_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdemography",
            name="in_game_rank_level",
            field=models.IntegerField(
                default=1,
                validators=[report.validators.validate_range_level],
                verbose_name="What is your in-game rank level?",
            ),
        ),
    ]
