# Generated by Django 4.2 on 2023-06-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0005_playerdemography_in_game_rank_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdemography",
            name="country",
            field=models.CharField(max_length=50),
        ),
    ]
